"""Constants for the Irrigation Scheduler integration."""

from __future__ import annotations

DOMAIN = "irrigation_scheduler"

CONF_VALVE_ENTITY = "valve_entity"
CONF_WEATHER_ENTITY = "weather_entity"
CONF_WATER_ENTITY = "water_entity"
CONF_INTERVAL_HOURS = "interval_hours"
CONF_RAIN_THRESHOLD_MM = "rain_threshold_mm"
CONF_RAIN_PROBABILITY = "rain_probability"
CONF_LOOKAHEAD_HOURS = "lookahead_hours"

DEFAULT_NAME = "Bewässerung"
DEFAULT_WINDOW_START = "06:00:00"
DEFAULT_WINDOW_END = "22:00:00"
DEFAULT_INTERVAL_HOURS = 24
DEFAULT_RAIN_THRESHOLD_MM = 2.0
DEFAULT_RAIN_PROBABILITY = 70
DEFAULT_LOOKAHEAD_HOURS = 12
DEFAULT_DURATION_MIN = 0

MAX_DURATION_MIN = 240

WEEKDAYS = ("mon", "tue", "wed", "thu", "fri", "sat", "sun")

RAIN_REFRESH_MINUTES = 30

STATUS_IDLE = "idle"
STATUS_WATERING = "watering"
STATUS_SKIPPED_RAIN = "skipped_rain"
STATUS_SKIPPED_NO_DURATION = "skipped_no_duration"
STATUS_ERROR = "error"
STATUSES = [
    STATUS_IDLE,
    STATUS_WATERING,
    STATUS_SKIPPED_RAIN,
    STATUS_SKIPPED_NO_DURATION,
    STATUS_ERROR,
]

HISTORY_DAYS = 90
SOURCE_AUTO = "auto"
SOURCE_MANUAL = "manual"
RESULT_COMPLETED = "completed"
RESULT_STOPPED = "stopped"
RESULT_ERROR = "error"

SIGNAL_UPDATE = f"{DOMAIN}_update"

PANEL_URL = "irrigation"
STATIC_URL = f"/{DOMAIN}_static"

OPTION_KEYS = (
    CONF_VALVE_ENTITY,
    CONF_WEATHER_ENTITY,
    CONF_INTERVAL_HOURS,
    CONF_RAIN_THRESHOLD_MM,
    CONF_RAIN_PROBABILITY,
    CONF_LOOKAHEAD_HOURS,
    CONF_WATER_ENTITY,
)
